FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    openssh-server=1:8.9p1-3ubuntu0.1 \
    python3-pip=22.0.2+dfsg-1ubuntu0.2 \
    python3=3.10.6-1~22.04

RUN mkdir -p /var/run/sshd

WORKDIR /app

COPY ../ .

#RUN pip install black

#ENTRYPOINT ["black", ".", "--check"]
ENTRYPOINT ["echo", "hey!"]
